name: Reusable Workflow for Spring Boot Gradle Monorepo
on:
    workflow_call:
        inputs:
            project-name:
                description: 'subproject name to build'
                required: true
                default: 'app-service-1'
                type: string
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Print current working directory
      run: pwd
        
    - name: List files to confirm contents - before build
      run: ls -F  

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 25

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Init gradle wrapper
      run: gradle wrapper

    - name: Change wrapper permissions
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew clean :${{inputs.project-name}}:build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: spring4-artifact
        path: ${{inputs.project-name}}/build/libs/*.jar

    - name: List files to confirm contents - after build
      run: ls -F  

    - name: Download arifact
      uses: actions/download-artifact@v5
      with:
        name: spring4-artifact

    - name: Display structure of downloaded files
      run: ls -R